/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcoesGerenciaisRouteImport } from './routes/acoes-gerenciais'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as CertificadoDigitalRouteImport } from './routes/certificado-digital'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ImportacaoRouteImport } from './routes/importacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PessoasRouteImport } from './routes/pessoas'
import { Route as PrefeiturasRouteImport } from './routes/prefeituras'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as VendasInternasRouteImport } from './routes/vendas-internas'
import { Route as RepresentantesIndexRouteImport } from './routes/representantes.index'
import { Route as RepresentantesSupervisorRouteImport } from './routes/representantes.$supervisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesGerenciaisRoute = AcoesGerenciaisRouteImport.update({
  id: '/acoes-gerenciais',
  path: '/acoes-gerenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoDigitalRoute = CertificadoDigitalRouteImport.update({
  id: '/certificado-digital',
  path: '/certificado-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacaoRoute = ImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasRoute = PessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefeiturasRoute = PrefeiturasRouteImport.update({
  id: '/prefeituras',
  path: '/prefeituras',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasInternasRoute = VendasInternasRouteImport.update({
  id: '/vendas-internas',
  path: '/vendas-internas',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesIndexRoute = RepresentantesIndexRouteImport.update({
  id: '/representantes/',
  path: '/representantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesSupervisorRoute =
  RepresentantesSupervisorRouteImport.update({
    id: '/representantes/$supervisor',
    path: '/representantes/$supervisor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoes-gerenciais': typeof AcoesGerenciaisRoute
  '/alertas': typeof AlertasRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/prefeituras': typeof PrefeiturasRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/vendas-internas': typeof VendasInternasRoute
  '/representantes/$supervisor': typeof RepresentantesSupervisorRoute
  '/representantes/': typeof RepresentantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoes-gerenciais': typeof AcoesGerenciaisRoute
  '/alertas': typeof AlertasRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/prefeituras': typeof PrefeiturasRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/vendas-internas': typeof VendasInternasRoute
  '/representantes/$supervisor': typeof RepresentantesSupervisorRoute
  '/representantes': typeof RepresentantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoes-gerenciais': typeof AcoesGerenciaisRoute
  '/alertas': typeof AlertasRoute
  '/certificado-digital': typeof CertificadoDigitalRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/importacao': typeof ImportacaoRoute
  '/login': typeof LoginRoute
  '/pessoas': typeof PessoasRoute
  '/prefeituras': typeof PrefeiturasRoute
  '/relatorios': typeof RelatoriosRoute
  '/suporte': typeof SuporteRoute
  '/vendas-internas': typeof VendasInternasRoute
  '/representantes/$supervisor': typeof RepresentantesSupervisorRoute
  '/representantes/': typeof RepresentantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoes-gerenciais'
    | '/alertas'
    | '/certificado-digital'
    | '/configuracoes'
    | '/contratos'
    | '/importacao'
    | '/login'
    | '/pessoas'
    | '/prefeituras'
    | '/relatorios'
    | '/suporte'
    | '/vendas-internas'
    | '/representantes/$supervisor'
    | '/representantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoes-gerenciais'
    | '/alertas'
    | '/certificado-digital'
    | '/configuracoes'
    | '/contratos'
    | '/importacao'
    | '/login'
    | '/pessoas'
    | '/prefeituras'
    | '/relatorios'
    | '/suporte'
    | '/vendas-internas'
    | '/representantes/$supervisor'
    | '/representantes'
  id:
    | '__root__'
    | '/'
    | '/acoes-gerenciais'
    | '/alertas'
    | '/certificado-digital'
    | '/configuracoes'
    | '/contratos'
    | '/importacao'
    | '/login'
    | '/pessoas'
    | '/prefeituras'
    | '/relatorios'
    | '/suporte'
    | '/vendas-internas'
    | '/representantes/$supervisor'
    | '/representantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoesGerenciaisRoute: typeof AcoesGerenciaisRoute
  AlertasRoute: typeof AlertasRoute
  CertificadoDigitalRoute: typeof CertificadoDigitalRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  ImportacaoRoute: typeof ImportacaoRoute
  LoginRoute: typeof LoginRoute
  PessoasRoute: typeof PessoasRoute
  PrefeiturasRoute: typeof PrefeiturasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SuporteRoute: typeof SuporteRoute
  VendasInternasRoute: typeof VendasInternasRoute
  RepresentantesSupervisorRoute: typeof RepresentantesSupervisorRoute
  RepresentantesIndexRoute: typeof RepresentantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes-gerenciais': {
      id: '/acoes-gerenciais'
      path: '/acoes-gerenciais'
      fullPath: '/acoes-gerenciais'
      preLoaderRoute: typeof AcoesGerenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado-digital': {
      id: '/certificado-digital'
      path: '/certificado-digital'
      fullPath: '/certificado-digital'
      preLoaderRoute: typeof CertificadoDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacao': {
      id: '/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof ImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas': {
      id: '/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefeituras': {
      id: '/prefeituras'
      path: '/prefeituras'
      fullPath: '/prefeituras'
      preLoaderRoute: typeof PrefeiturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas-internas': {
      id: '/vendas-internas'
      path: '/vendas-internas'
      fullPath: '/vendas-internas'
      preLoaderRoute: typeof VendasInternasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes/': {
      id: '/representantes/'
      path: '/representantes'
      fullPath: '/representantes/'
      preLoaderRoute: typeof RepresentantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes/$supervisor': {
      id: '/representantes/$supervisor'
      path: '/representantes/$supervisor'
      fullPath: '/representantes/$supervisor'
      preLoaderRoute: typeof RepresentantesSupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoesGerenciaisRoute: AcoesGerenciaisRoute,
  AlertasRoute: AlertasRoute,
  CertificadoDigitalRoute: CertificadoDigitalRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  ImportacaoRoute: ImportacaoRoute,
  LoginRoute: LoginRoute,
  PessoasRoute: PessoasRoute,
  PrefeiturasRoute: PrefeiturasRoute,
  RelatoriosRoute: RelatoriosRoute,
  SuporteRoute: SuporteRoute,
  VendasInternasRoute: VendasInternasRoute,
  RepresentantesSupervisorRoute: RepresentantesSupervisorRoute,
  RepresentantesIndexRoute: RepresentantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
